version: "3.2"

services:
  bonus-calc-listener:
    image: bonus-calc-listener
    build:
      context: .
      dockerfile: BonusCalcListener/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
     - ENVIRONMENT=LocalDevelopment
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local

  bonus-calc-listener-test:
    image: bonus-calc-listener-test
    build:
      context: .
      dockerfile: BonusCalcListener.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - ENVIRONMENT=LocalDevelopment
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - DB_HOST=test-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
      - DB_DATABASE=testdb
      - TZ=Europe/London
    depends_on:
      - test-database

  test-database:
    image: postgres:12
    ports:
      - 5435:5432
    env_file:
      - database.env
    volumes:
      - ./database/init-testdb.sql:/docker-entrypoint-initdb.d/init-testdb.sql
