version: "3.2"

services:
  bonus-calc-listener:
    image: bonus-calc-listener
    build:
      context: .
      dockerfile: BonusCalcListener/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
     - ENVIRONMENT=LocalDevelopment
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local

  bonus-calc-listener-test:
    image: bonus-calc-listener-test
    build:
      context: .
      dockerfile: BonusCalcListener.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - ENVIRONMENT=LocalDevelopment
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
